### ISSUE TITLE
Illuminance component broken in 0.89

### ISSUE THREAD

**Issue by danodemano** [pnbruckner/homeassistant-config#111]
Looks to be similar to #83 

```
2019-03-07 08:26:35 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.illuminance.sensor. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/loader.py", line 166, in _load_file
    module = importlib.import_module(path)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/root/.homeassistant/custom_components/illuminance/sensor.py", line 25, in <module>
    from homeassistant.components.sensor.yr import (
ImportError: cannot import name 'CONF_ATTRIBUTION'
2019-03-07 08:26:35 ERROR (MainThread) [homeassistant.loader] Unable to find platform illuminance.
```

```yaml
- platform: illuminance
  name: Outside Illuminance
  entity_id: weather.dark_sky
```

**Comment by pnbruckner** [comment]
>Looks to be similar to #83

Similar, yes, but a different problem this time. Just trying to keep up with the Great Migration, which apparently is still migrating...

**Comment by pnbruckner** [comment]
For some reason they decided to change CONF_ATTRIBUTION to ATTRIBUTION in [PR #21069](https://github.com/home-assistant/home-assistant/pull/21069).

**Comment by danodemano** [comment]
Oh, now that's special.  At least that's easy enough to fix I suppose.

**Comment by pnbruckner** [comment]
The same thing happened with the 0.85 release, but with the Dark Sky Sensor. Yes, easy enough to fix.
