### ISSUE TITLE
Amcrest streaming broken in 0.91.0

### ISSUE THREAD

**Issue by GaryOkie** [pnbruckner/homeassistant-config#128]
custom Amcrest component will load OK under .91.0,  snapshots in preview are OK, but streaming is completely broken.    Numerous errors (logs below).      91.0 release notes show an update to Amcrest was made to [SUPPORT_STREAM](https://github.com/home-assistant/home-assistant/pull/22553).  

I temporarily removed the custom Amcrest code and tried the official.   It won't even load!   I won't list those errors here since that's not relevant to the custom code.   Looks like I will either have to back out to .90 or hope .91.1 fixes it.   

```
2019-04-05 10:04:06 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/http/real_ip.py", line 33, in real_ip_middleware
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/http/ban.py", line 68, in ban_middleware
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/http/auth.py", line 216, in auth_middleware
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/http/view.py", line 114, in handle
    result = await result
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/camera/__init__.py", line 475, in get
    return await self.handle(request, camera)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/camera/__init__.py", line 511, in handle
    return await camera.handle_async_mjpeg_stream(request)
  File "/config/custom_components/amcrest/camera.py", line 206, in handle_async_mjpeg_stream
    from haffmpeg import CameraMjpeg
ImportError: cannot import name 'CameraMjpeg' from 'haffmpeg' (/usr/local/lib/python3.7/site-packages/haffmpeg/__init__.py)
2019-04-05 10:04:34 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/http/real_ip.py", line 33, in real_ip_middleware
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/http/ban.py", line 68, in ban_middleware
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/http/auth.py", line 216, in auth_middleware
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/http/view.py", line 114, in handle
    result = await result
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/camera/__init__.py", line 475, in get
    return await self.handle(request, camera)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/camera/__init__.py", line 511, in handle
    return await camera.handle_async_mjpeg_stream(request)
  File "/config/custom_components/amcrest/camera.py", line 206, in handle_async_mjpeg_stream
    from haffmpeg import CameraMjpeg
ImportError: cannot import name 'CameraMjpeg' from 'haffmpeg' (/usr/local/lib/python3.7/site-packages/haffmpeg/__init__.py)
2019-04-05 10:04:43 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/http/real_ip.py", line 33, in real_ip_middleware
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/http/ban.py", line 68, in ban_middleware
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/http/auth.py", line 216, in auth_middleware
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/http/view.py", line 114, in handle
    result = await result
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/camera/__init__.py", line 475, in get
    return await self.handle(request, camera)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/camera/__init__.py", line 511, in handle
    return await camera.handle_async_mjpeg_stream(request)
  File "/config/custom_components/amcrest/camera.py", line 206, in handle_async_mjpeg_stream
    from haffmpeg import CameraMjpeg
ImportError: cannot import name 'CameraMjpeg' from 'haffmpeg' (/usr/local/lib/python3.7/site-packages/haffmpeg/__init__.py)
2019-04-05 10:05:02 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/http/real_ip.py", line 33, in real_ip_middleware
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/http/ban.py", line 68, in ban_middleware
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/http/auth.py", line 216, in auth_middleware
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/http/view.py", line 114, in handle
    result = await result
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/camera/__init__.py", line 475, in get
    return await self.handle(request, camera)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/camera/__init__.py", line 511, in handle
    return await camera.handle_async_mjpeg_stream(request)
  File "/config/custom_components/amcrest/camera.py", line 206, in handle_async_mjpeg_stream
    from haffmpeg import CameraMjpeg
ImportError: cannot import name 'CameraMjpeg' from 'haffmpeg' (/usr/local/lib/python3.7/site-packages/haffmpeg/__init__.py)
2019-04-05 10:07:59 ERROR (MainThread) [aiohttp.server] Error handling request
```

**Comment by pnbruckner** [comment]
They changed the version of haffmpeg to a major new version and the interface apparently changed. I haven't updated the custom_component per those recent changes yet as I'm obviously focusing on getting all of my new features folded into the standard component.

I can try and spend some time getting the custom_component updated, again, to work with the latest HA releases, but honestly, that's starting to become a huge undertaking. Once I've gotten all the features I want folded into the standard component I'm planning on dropping all support for this custom component (and maybe even deleting it from github.) Not sure about that yet, though.

So, in the meantime, you can check out all the [recent commits](https://github.com/home-assistant/home-assistant/commits/dev/homeassistant/components/amcrest) to the amcrest component and merge any of the ones _I didn't do_ into your copy of my custom component, or you can revert back to a version of HA that it works with.

Sorry, but things are a bit hectic right now with working towards updating the standard component.

**Comment by GaryOkie** [comment]
I see that .91.1 was just released a few hours ago, so I'll give that a try first with the standard component.   It might have all your updates I need in it.     May have to wait a day for the Hassio/RPi build though.    

I didn't see any issues reported (yet) for Amcrest, but there was a fix added for Foscam.   And in case you're curious - here's the error that keeps the standard component from even loading...  

  
```
2019-04-05 10:40:43 ERROR (MainThread) [homeassistant.setup] Error during setup of component amcrest
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 154, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/amcrest/__init__.py", line 95, in setup
    from amcrest import AmcrestCamera, AmcrestError
ImportError: cannot import name 'AmcrestCamera' from 'amcrest' (/config/amcrest/__init__.py)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/automation/__init__.py", line 380, in action
    await script_obj.async_run(variables, context)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/script.py", line 131, in async_run
    await self._handle_action(action, variables, context)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/script.py", line 210, in _handle_action
    action, variables, context)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/script.py", line 299, in _async_call_service
    context=context
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 88, in async_call_from_config
    domain, service_name, service_data, blocking=blocking, context=context)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1138, in async_call
    self._execute_service(handler, service_call))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1160, in _execute_service
    await handler.func(service_call)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_component.py", line 188, in handle_service
    self._platforms.values(), func, call, service_name
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 314, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 330, in _handle_service_platform_call
    await func(entity, data)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/camera/__init__.py", line 618, in async_handle_snapshot_service
    image = await camera.async_camera_image()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/proxy/camera.py", line 228, in async_camera_image
    self._proxied_camera)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/camera/__init__.py", line 127, in async_get_image
    camera = _get_camera_from_entity_id(hass, entity_id)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/camera/__init__.py", line 197, in _get_camera_from_entity_id
    raise HomeAssistantError('Camera not found')
homeassistant.exceptions.HomeAssistantError: Camera not found

```

**Comment by pnbruckner** [comment]
I just looked at the HA issue you filed. There is something very strange about it. It seems to be having a problem using the amcrest package from pypi.org. I haven't tried specifically with 0.91.x, but I'm using a dev checkout that says it's "0.92.0.dev0", and it's working fine. I know you're using hassio, which I also know makes it hard to do things, but is there anyway you can check to see if the amcrest package version 1.3.0 is properly installed in the Python environment in which HA runs?

**Comment by GaryOkie** [comment]
I'll sure try to find it.   where would you find it in your non-hassio build?

**Comment by GaryOkie** [comment]
Hmm,  based on the "amcrest-1.2.7.dist-info" label, it appears that it is not loading 1.3.0.  (see the very end of this list).    
```

/config/deps/lib/python3.7/site-packages/amcrest/ptz.py
/config/deps/lib/python3.7/site-packages/amcrest/video.py
/config/deps/lib/python3.7/site-packages/amcrest/snapshot.pyc
/config/deps/lib/python3.7/site-packages/amcrest/storage.py
/config/deps/lib/python3.7/site-packages/amcrest/system.py
/config/deps/lib/python3.7/site-packages/amcrest/snapshot.py
/config/deps/lib/python3.7/site-packages/amcrest/record.pyc
/config/deps/lib/python3.7/site-packages/amcrest/Makefile
/config/deps/lib/python3.7/site-packages/amcrest/record.py
/config/deps/lib/python3.7/site-packages/amcrest/http.py
/config/deps/lib/python3.7/site-packages/amcrest/system.pyc
/config/deps/lib/python3.7/site-packages/amcrest/exceptions.py
/config/deps/lib/python3.7/site-packages/amcrest/audio.py
/config/deps/lib/python3.7/site-packages/amcrest/user_management.py
/config/deps/lib/python3.7/site-packages/amcrest/log.pyc
/config/deps/lib/python3.7/site-packages/amcrest/audio.pyc
/config/deps/lib/python3.7/site-packages/amcrest/motion_detection.py
/config/deps/lib/python3.7/site-packages/amcrest/http.pyc
/config/deps/lib/python3.7/site-packages/amcrest/event.pyc
/config/deps/lib/python3.7/site-packages/amcrest/utils.py
/config/deps/lib/python3.7/site-packages/amcrest/nas.pyc
/config/deps/lib/python3.7/site-packages/amcrest/event.py
/config/deps/lib/python3.7/site-packages/amcrest/nas.py
/config/deps/lib/python3.7/site-packages/amcrest/video.pyc
/config/deps/lib/python3.7/site-packages/amcrest/storage.pyc
/config/deps/lib/python3.7/site-packages/amcrest/special.pyc
/config/deps/lib/python3.7/site-packages/amcrest/utils.pyc
/config/deps/lib/python3.7/site-packages/amcrest/ptz.pyc
/config/deps/lib/python3.7/site-packages/amcrest/__init__.pyc
/config/deps/lib/python3.7/site-packages/amcrest/Makefile.in
/config/deps/lib/python3.7/site-packages/amcrest/__init__.py
/config/deps/lib/python3.7/site-packages/amcrest/motion_detection.pyc
/config/deps/lib/python3.7/site-packages/amcrest/exceptions.pyc
/config/deps/lib/python3.7/site-packages/amcrest/network.py
/config/deps/lib/python3.7/site-packages/amcrest/special.py
/config/deps/lib/python3.7/site-packages/amcrest/Makefile.am
/config/deps/lib/python3.7/site-packages/amcrest/log.py
/config/deps/lib/python3.7/site-packages/amcrest/network.pyc
/config/deps/lib/python3.7/site-packages/amcrest/user_management.pyc
/config/deps/lib/python3.7/site-packages/amcrest/config.py
/config/deps/lib/python3.7/site-packages/amcrest-1.2.7.dist-info
/config/deps/lib/python3.7/site-packages/amcrest-1.2.7.dist-info/RECORD
/config/deps/lib/python3.7/site-packages/amcrest-1.2.7.dist-info/top_level.txt
/config/deps/lib/python3.7/site-packages/amcrest-1.2.7.dist-info/WHEEL
/config/deps/lib/python3.7/site-packages/amcrest-1.2.7.dist-info/zip-safe
/config/deps/lib/python3.7/site-packages/amcrest-1.2.7.dist-info/INSTALLER
/config/deps/lib/python3.7/site-packages/amcrest-1.2.7.dist-info/METADATA
/config/deps/lib/python3.7/site-packages/amcrest-1.2.7.dist-info/COPYING
/config/deps/lib/python3.7/site-packages/amcrest-1.2.7.dist-info/
```

**Comment by pnbruckner** [comment]
Oops, sorry. Yes, for 0.91.x it _should_ be 1.2.7. It gets bumped to 1.3.0 in a merged PR that has not made a release yet.

**Comment by pnbruckner** [comment]
Hmm, and of course, the custom component already wants 1.3.0. You may want to completely remove the custom component, and restart HA, and see what happens using the standard component. If that works then at least you can close the other issue, and then we can go from there.

**Comment by GaryOkie** [comment]
by "completely remove",  wouldn't simply moving the entire amcrest directory out of custom_components into a different dir accomplish that?   That's what I've already done.   Should I also delete the py cache?

**Comment by pnbruckner** [comment]
Yeah that should be ok. The package requirement gets processed when the component is loaded, so depending on which gets loaded (custom or standard) HA should make sure the right package version is installed. But the error seems to imply either the package isn't installed correctly or is corrupted somehow. Maybe try deleting the python cache folder/files in the amcrest package directory.

**Comment by GaryOkie** [comment]
I had already deleted all pyc's in the __pycache___ folder and restarted (but had not stopped HA first).  

Anyway, it didn't help.   Still get this at HA startup...

```

Error during setup of component amcrest
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 154, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/amcrest/__init__.py", line 95, in setup
    from amcrest import AmcrestCamera, AmcrestError
ImportError: cannot import name 'AmcrestCamera' from 'amcrest' (/config/amcrest/__init__.py)
```

**Comment by GaryOkie** [comment]
I see a bunch of pyc's in the parent amcrest dir...   maybe these should be deleted too?

``
/config/deps/lib/python3.7/site-packages/amcrest
```

Makefile              config.pyc            motion_detection.py   record.pyc            user_management.py
Makefile.am           event.py              motion_detection.pyc  snapshot.py           user_management.pyc
Makefile.in           event.pyc             nas.py                snapshot.pyc          utils.py
__init__.py           exceptions.py         nas.pyc               special.py            utils.pyc
__init__.pyc          exceptions.pyc        network.py            special.pyc           video.py
__pycache__           http.py               network.pyc           storage.py            video.pyc
audio.py              http.pyc              ptz.py                storage.pyc
audio.pyc             log.py                ptz.pyc               system.py
config.py             log.pyc               record.py             system.pyc
```

**Comment by pnbruckner** [comment]
Wait, I think I see what it's trying to do. The standard component (`.../site-packages/homeassistant/components/amcrest/__init__.py`), when trying to import from the pypi.org package `amcrest`, is instead importing from the custom HA amcrest component, i.e., `/config/amcrest/__init__.py`.

Are you sure `/config/amcrest/...` is gone? Maybe get rid of `/config/__pycache__` if it exists, too.

**Comment by pnbruckner** [comment]
To answer your last question, I did suggest removing those .pyc files, too. But they're there because the amcrest package still has Python2 support and when it gets installed I think those Python2 cache files get created. They probably don't matter.

**Comment by GaryOkie** [comment]
Oh crap,   I just moved amcrest folder out of custom_components back 1 level (config/amcrest) thinking that would remove it from loading pattern.  I didn't realize HA would also look in config folder too.

will take care of this oversight right now...

**Comment by pnbruckner** [comment]
FWIW, I would not have expected that either.

**Comment by GaryOkie** [comment]
All good now - thanks for your help!   I will update and close the main HA issue now.

Should I leave this one open for a short while in case others run into the same .91 issue with your component?

**Comment by pnbruckner** [comment]
Yep, leave it open. There's still the issue of the recent HA changes that the custom component hasn't caught up with. You'll see there's another open issue with 0.91, but with my custom illumninance component -- in that case it's due to the last pieces of the Great Migration.

**Comment by pnbruckner** [comment]
@GaryOkie see PR #129 for an update that should fix this issue. If you give it a try, please let me know how it works. I haven't tested it at all.

**Comment by GaryOkie** [comment]
Hi Phil - yep, this update  fixes your custom Amcrest streaming in .91.x - nice work!

I do have to admit that in switching back to the standard Amcrest component (in .91) I was really liking the latest improvements to streaming that was added  (such as pre-caching).   It really made a difference.   

I think I will switch back to the standard component and closely watch your PR's make their way.   I can also jump in to help test if needed on a spare system I have.

**Comment by pnbruckner** [comment]
Cool! FWIW, my current PR is #22703. It adds a binary_sensor (motion_detected) to take the place of the motion_dectector sensor. (But I think you already knew that. :smile:) Next up will be adding services and deprecating the switches.
