### ISSUE TITLE
Life360 local variable 'api' referenced before assignment

### ISSUE THREAD

**Issue by c0rnflake** [pnbruckner/homeassistant-config#138]
I've just updated the component to 2.9.3 and I'm getting the following error:

2019-04-22 08:54:30 WARNING (SyncWorker_12) [custom_components.life360.device_tracker] Ignoring: TypeError: __init__() takes from 2 to 4 positional arguments but 6 were given
2019-04-22 08:54:30 ERROR (MainThread) [homeassistant.components.device_tracker] Error setting up platform life360
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/device_tracker/__init__.py", line 184, in async_setup_platform
    disc_info)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/life360/device_tracker.py", line 295, in setup_scanner
    Life360Scanner(hass, config, see, interval, home_place_name, members, api)
UnboundLocalError: local variable 'api' referenced before assignment

I'm running HA 0.91.4

Entities are no longer showing up on the map card or being updated in sensor cards.  The entities do not have any gps data etc.

**Comment by dannyhanes** [comment]
Similar issue here: 
Home Assistant: 0.91.3
Life360 Version: 2.9.3

```
Error setting up platform life360

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/device_tracker/__init__.py", line 184, in async_setup_platform
    disc_info)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/life360/device_tracker.py", line 295, in setup_scanner
    Life360Scanner(hass, config, see, interval, home_place_name, members, api)
UnboundLocalError: local variable 'api' referenced before assignment`

**Comment by pnbruckner** [comment]
I did test with 0.91.4, but maybe not well enough. It might be because I had to add `__init__.py` (so that custom_updater would be happy), that now the `import from life360 ...` statement is getting confused and finding `custom_components/life360/__init__.py` instead of the life360 package from pypi.org. Working on it...

**Comment by pnbruckner** [comment]
So I installed HA 0.94.1. I made sure life360, timezonefinderL & numpy were all uninstalled. I even deleted known_devices.yaml and the HA database. I then started HA and used custom_updater to install element `device_tracker.life360`. That worked. Here is the log output:
```text
2019-04-22 09:25:21 INFO (MainThread) [pyupdate.log] CustomComponents(upgrade_single) - device_tracker.life360 started
2019-04-22 09:25:22 INFO (MainThread) [pyupdate.log] CustomComponents(update_requirements ) - life360==3.0.0
Collecting life360==3.0.0
  Using cached https://files.pythonhosted.org/packages/ba/59/c539a662948ad743130ce2cb3001b6a1e0b1064effe9ccd4ad5858ce96e0/life360-3.0.0-py3-none-any.whl
Requirement already satisfied, skipping upgrade: requests in ./lib/python3.6/site-packages (from life360==3.0.0) (2.21.0)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in ./lib/python3.6/site-packages (from requests->life360==3.0.0) (2019.3.9)
Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in ./lib/python3.6/site-packages (from requests->life360==3.0.0) (1.24.1)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in ./lib/python3.6/site-packages (from requests->life360==3.0.0) (2.8)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in ./lib/python3.6/site-packages (from requests->life360==3.0.0) (3.0.4)
Installing collected packages: life360
Successfully installed life360-3.0.0
2019-04-22 09:25:23 INFO (MainThread) [pyupdate.log] CustomComponents(update_requirements ) -
Invalid requirement: ''

2019-04-22 09:25:24 INFO (MainThread) [pyupdate.log] CustomComponents(update_requirements ) - timezonefinderL==2.0.1
Collecting timezonefinderL==2.0.1
  Using cached https://files.pythonhosted.org/packages/36/42/ed0982bf05e4b6512d270f6eac0364d6d284b304d87a43bb610181c87a85/timezonefinderL-2.0.1-py2.py3-none-any.whl
Collecting numpy (from timezonefinderL==2.0.1)
  Downloading https://files.pythonhosted.org/packages/c1/e2/4db8df8f6cddc98e7d7c537245ef2f4e41a1ed17bf0c3177ab3cc6beac7f/numpy-1.16.3-cp36-cp36m-manylinux1_x86_64.whl (17.3MB)
    100% |████████████████████████████████| 17.3MB 1.5MB/s
Installing collected packages: numpy, timezonefinderL
Successfully installed numpy-1.16.3 timezonefinderL-2.0.1
2019-04-22 09:25:30 INFO (MainThread) [pyupdate.log] CustomComponents(upgrade_single) - device_tracker.life360 finished
```
I then added life360 to configuration.yaml and restarted HA. It started fine and life360 is working fine for me.

I'm not sure why you're seeing those errors.

**Comment by pnbruckner** [comment]
So I think this is the clue:
```text
2019-04-22 08:54:30 WARNING (SyncWorker_12) [custom_components.life360.device_tracker] Ignoring: TypeError: __init__() takes from 2 to 4 positional arguments but 6 were given
```
That seems to be implying that it is indeed finding the wrong life360 class. But custom_components/life360 doesn't define any class with that name. So what is it finding?

Can you stop HA, the go to a command line, and make sure you're running in the same context as HA would, and run this command:
```text
pip list | grep life360
```
What do you get?

**Comment by c0rnflake** [comment]
I'm running HA on a Pi 3b+ in docker, pip returns -bash: pip: command not found

**Comment by pnbruckner** [comment]
I think I may have figured it out. When I put the REQUIREMENTS and DEPENDENCIES back in, I put them in the wrong place. I put them in `__init__.py` when they need to be in `device_tracker.py` (where they used to be. I'll release a fix ASAP.

**Comment by c0rnflake** [comment]
Thanks for the quick fix, everything is now working as it should
