### ISSUE TITLE
Type is not JSON serializable: RGBColor

### ISSUE THREAD

**Issue by cooljimy84** [pnbruckner/homeassistant-config#160]
Not sure if you can do any thing about this error with HASS 2022.07.03 (and .2 and .1) as i think i really need to remove the colour name in my ESPHOME MQTT lights (tho as the transitions are woken i've not updated them for an age)

```
2022-07-13 21:23:19 WARNING (MainThread) [homeassistant.components.light.reproduce_state] The use of other attributes than device state attributes is deprecated and will be removed in a future release. Invalid attributes are ['color_name']. Read the logs for further details: https://www.home-assistant.io/integrations/scene/
2022-07-13 21:23:19 ERROR (MainThread) [homeassistant.components.automation.night_time_door_alert] Night time door alert: Error executing script. Unexpected error for call_service at pos 3: Type is not JSON serializable: RGBColor
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/service.py", line 717, in _handle_entity_call
    await result
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/scene/__init__.py", line 114, in _async_activate
    await self.async_activate(**kwargs)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/homeassistant/scene.py", line 327, in async_activate
    await async_reproduce_state(
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/state.py", line 116, in async_reproduce_state
    await asyncio.gather(
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/state.py", line 110, in worker
    await platform.async_reproduce_states(
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/light/reproduce_state.py", line 198, in async_reproduce_states
    await asyncio.gather(
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/light/reproduce_state.py", line 185, in _async_reproduce_state
    await hass.services.async_call(
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/service.py", line 717, in _handle_entity_call
    await result
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/light/__init__.py", line 553, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/wled/helpers.py", line 17, in handler
    await func(self, *args, **kwargs)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/wled/light.py", line 246, in async_turn_on
    await self.coordinator.wled.segment(**data)
  File "/srv/homeassistant/lib/python3.9/site-packages/wled/wled.py", line 481, in segment
    await self.request("/json/state", method="POST", data=state)
  File "/srv/homeassistant/lib/python3.9/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.9/site-packages/wled/wled.py", line 178, in request
    response = await self.session.request(
  File "/srv/homeassistant/lib/python3.9/site-packages/aiohttp/client.py", line 408, in _request
    data = payload.JsonPayload(json, dumps=self._json_serialize)
  File "/srv/homeassistant/lib/python3.9/site-packages/aiohttp/payload.py", line 398, in __init__
    dumps(value).encode(encoding),
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/aiohttp_client.py", line 101, in <lambda>
    json_serialize=lambda x: orjson.dumps(x).decode("utf-8"),
TypeError: Type is not JSON serializable: RGBColor
```

**Comment by cooljimy84** [comment]
I don't think it does, as it seems to happen for others without the use of this script.
