### ISSUE TITLE
Error when trying to save lights state

### ISSUE THREAD

**Issue by majkers** [pnbruckner/homeassistant-config#165]
I've noticed that one time my automation to store light state didn't work. It is working in 99,99% cases but this time it failed. Hard for me to understand why so let me bring some context to help to fix it. I had 3 lights on (1x IKEA m 2xHue) all connected to Hue bridge. I turned off with wall switch 2xHue and after some time my automation to store light state should work. IMHO those Hue lights might not become unavailable before automation tried to store their state. Anyway. This is a log file containing error:

I am running 1.3.0 version of script

```
Logger: homeassistant.components.automation.przygas_swiatlo_w_salonie
Source: helpers/script.py:468
Integration: Automatyzacja (documentation, issues)
First occurred: 6 grudnia 2023 18:34:19 (1 occurrences)
Last logged: 6 grudnia 2023 18:34:19

Przygas swiatlo w salonie: Error executing script. Unexpected error for call_service at pos 1: AST constructor recursion depth mismatch (before=33, after=76)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2035, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2079, in _execute_service
    return await self._hass.async_add_executor_job(target, service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 112, in python_script_service_handler
    execute_script(hass, call.service, call.data)
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 146, in execute_script
    execute(hass, filename, source, data)
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 153, in execute
    compiled = compile_restricted_exec(source, filename=filename)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/RestrictedPython/compile.py", line 87, in compile_restricted_exec
    return _compile_restricted_mode(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/RestrictedPython/compile.py", line 52, in _compile_restricted_mode
    c_ast = ast.parse(source, filename, mode)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SystemError: AST constructor recursion depth mismatch (before=33, after=76)


**************

Logger: homeassistant.components.automation.przygas_swiatlo_w_salonie
Source: components/automation/__init__.py:655
Integration: Automatyzacja (documentation, issues)
First occurred: 6 grudnia 2023 18:34:19 (1 occurrences)
Last logged: 6 grudnia 2023 18:34:19

While executing automation automation.przygas_swiatlo_w_salonie
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 655, in async_trigger
    await self.action_script.async_run(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1578, in async_run
    return await asyncio.shield(run.async_run())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 420, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 470, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 493, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2035, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2079, in _execute_service
    return await self._hass.async_add_executor_job(target, service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 112, in python_script_service_handler
    execute_script(hass, call.service, call.data)
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 146, in execute_script
    execute(hass, filename, source, data)
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 153, in execute
    compiled = compile_restricted_exec(source, filename=filename)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/RestrictedPython/compile.py", line 87, in compile_restricted_exec
    return _compile_restricted_mode(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/RestrictedPython/compile.py", line 52, in _compile_restricted_mode
    c_ast = ast.parse(source, filename, mode)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SystemError: AST constructor recursion depth mismatch (before=33, after=76)
```

**Comment by pnbruckner** [comment]
A Google search of "AST constructor recursion depth mismatch" seems to indicate this is an issue with the standard ast Python library, or at least, in Home Assistant Core's use of it. I don't believe there is anything that can be done about it in this custom `python_script`. Closing for now, but feel free to reopen if there is any indication that a change in this script can resolve, or at least avoid, this problem.
