### ISSUE TITLE
Amcrest:  Empty SDCard throws error

### ISSUE THREAD

**Issue by GaryOkie** [pnbruckner/homeassistant-config#85]
I see that you have a PR to merge your enhancements into the standard Amcrest component - that's great!  I'm using your custom code and it's working nicely, but I'm happy to see it officially incorporated.

One very slight issue I ran into that can easily be ignored, but thought it would be good to point out.   If a new SDCard is installed (or not present) the sensor logic for reporting the SDCard disk usage throws an index error and no sensor entity is created.

Does it make sense to include a fix for this to be included in your PR?     If not, you can close this as it's really a minor issue that should go away once data is written to the card.
```
2019-01-11 08:27:25 ERROR (MainThread) [homeassistant.components.sensor] amcrest: Error on device update!
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 248, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 349, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/sensor/amcrest.py", line 103, in update
    sd_used = self._camera.storage_used
  File "/usr/local/lib/python3.6/site-packages/amcrest/storage.py", line 39, in storage_used
    status = [s for s in ret.split() if '.UsedBytes=' in s][0]
IndexError: list index out of range
```

**Comment by GaryOkie** [comment]
ok, will do!   

Thanks
